service: molecule-parser

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128
plugins:
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
